src/api/auth.js
src/api/storage.js
src/components/layout/Header.vue
src/components/layout/LoginModal.vue
src/main.js
src/store/authStore.js

`feature/social-login` -> `dev`
소셜 로그인 구현
+ supabase provider 계정 정보 => 윤슬
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
2-featuresocial-login

[merge / social-login] :sparkles:Feature 소셜 로그인(구글, 깃허브)

---

tailwind.config.js

`12-styletailwindcss-edit-colorchip` -> `dev`
검정, 남색, 회색 컬러칩 추가
- 세빈님이 피그마에 작성하신 컬러칩 그대로 넘버링 했습니당!
[[이슈 번호/정보](이슈 url)](https://github.com/devcourse-Teemo/devcourse-Teemo/issues/12)

:lipstick:Style: tailwind.config.js 컬러칩 변경 추가

---

src/main.js
src/pages/ProblemBoardDetail.vue
src/pages/ProblemBoardDetailUpdate.vue
src/router/index.js
src/store/authStore.js

`style/edit-problem` -> `dev`
문제 수정 페이지 퍼블리싱, 문제 상세 페이지 수정
- 수정하기 버튼에 ProblemBoardDetailUpdate.vue으로 라우팅 처리
기능 개발하면서 post도 추가하겠습니당
style/edit-problem #39 (https://github.com/devcourse-Teemo/devcourse-Teemo/issues/39)

💄Style: 문제 수정 페이지 퍼블리싱

---

src/api/auth.js
src/api/workbook.js
src/components/layout/Header.vue
src/components/layout/LoginModal.vue
src/main.js
src/pages/LandingPage.vue
src/pages/create-exam-room/CreateExamRoom.vue
src/pages/create-exam-room/components/MyWorkBook.vue
src/pages/create-exam-room/components/SelectDateTime.vue
src/pages/create-exam-room/components/SelectParticipants.vue
src/pages/create-exam-room/components/SelectWorkbook.vue
src/pages/create-exam-room/components/SelectionChip.vue
src/pages/create-exam-room/components/UserListItem.vue
src/utils/imageUtils.js
vite.config.js

`feature/create-exam-room` -> `dev`
내 문제집 목록 불러오기
문제집 선택시 chips에 표시
랜딩 페이지 로그인 모달 연결 
모달 레이아웃 깨짐 수정
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
[feature/problem-detail]https://github.com/devcourse-Teemo/devcourse-Teemo/issues/41

✨Feature: 내 문제집 목록 불러오기 /🚨 Fix: 랜딩 페이지 로그인 모달 연결 / 모달 레이아웃 깨짐 수정

---

src/api/follow.js
src/api/problem.js
src/api/workbook.js
src/components/layout/ProblemSet.vue
src/components/layout/ProblemTable.vue
src/pages/Mypage/components/MypageTabs.vue
src/pages/user-profile/UserProfile.vue
src/pages/user-profile/components/UserProfileTabs.vue

`feature/user-profile` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#53

✨ Feature: 유저 프로필 페이지 기능 구현

---

src/components/CommentList.vue
src/components/layout/Comment.vue
src/components/layout/ProblemSet.vue
src/components/layout/ProblemTable.vue
src/main.js
src/pages/exam-environment/components/TestSidebar.vue
src/pages/exam-history/components/examHistoryTable.vue
src/pages/problem-detail/ProblemBoardDetail.vue
src/pages/problem-detail/components/CommentList.vue
src/pages/problem-detail/components/ProblemHeader.vue
src/router/index.js
src/store/problemStore.js
vite.config.js

`fix/ProbelmBoardDetail` -> `dev`
게시판에 접속하면 타입 불일치로 인한 오류가 계속 개발자 도구에 남음.
problem, author는 ProblemHeader에서 props 전달 과정에서 default 값이 설정 누락.
hasLiked는 problemStore에서 누락되어서 data를 찾지 못 하는 오류가 발생함.
problemStore.js 에서 누락된 데이터 및 초기값 타입을 맞춰주었습니다.
잘못 전달되고있던 props와 데이터의 타입을 추가하였습니다.
ProblemSet.vue에 옵셔널 체이닝을 추가 했습니다.
불필요한 import 구문을 없앴습니다. (터미널에서 계속 지우라고해서...)
defineProps 와 defineEmits 은 Vue 3 이후부터 import 구문을 안써도 사용할 수 있게 변경되었습니다.
pull 받아보시고 잘 구동 되는지 확인해주세요 👍
없습니다.
좋아요 기능 구현하려고 하는데 RLS 오류가 나오네요!

Fix/problem board detail 게시판 오류 수정

---

src/api/auth.js
src/api/index.js
src/api/token.js
src/components/layout/Header.vue
src/components/layout/LoginModal.vue
src/pages/LandingPage.vue
src/pages/NotFound.vue
src/pages/ProblemSetBoardDetail.vue
src/pages/problem-board/ProblemBoard.vue
src/router/index.js
src/store/authStore.js

✨solved relogin problem

---

src/api/auth.js
src/components/layout/Header.vue
src/router/index.js

✨ solved relogin problem

---

src/api/token.js
src/pages/Home.vue
src/pages/LandingPage.vue
src/router/index.js

✨ login division

---

src/api/problem.js
src/api/testResult.js
src/components/layout/Search.vue
src/pages/exam-history/ExamHistory.vue
src/pages/exam-history/components/examHistoryTable.vue
src/pages/problem-board/ProblemBoard.vue

`feature/exam-history` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#65

✨ Feature: 시험 내역 페이지 기능 구현

---

src/api/comment.js
src/api/problemLike.js
src/api/testCenter.js
src/components/layout/LoginModal.vue
src/pages/LandingPage.vue
src/pages/exam-room/ExamRoom.vue
src/pages/exam-room/components/ExamCard.vue
src/pages/exam-room/components/InvitedExamCard.vue
src/pages/problem-detail/ProblemBoardDetail.vue
src/pages/problem-detail/components/CommentList.vue
src/pages/problem-detail/components/ProblemHeader.vue
src/utils/simpleDateTimeFormat.js

`feature/🚨Fix-problem-detail` -> `dev`
문제 상세 페이지
문제 작성자 = 로그인 한 사용자 여부에 따라 UI 구현
댓글 기능 구현 (수정 제외) / 좋아요 기능 구현
북마크 기능은 추후 구현 예정
테이블 삭제는 policy 설정이 필요하다... 메모메모
북마크 기능은 상대적으로 우선 순위가 낮은 것 같아 추후 개발하겠습니당
feature/🚨Fix-problem-detail #68 (https://github.com/devcourse-Teemo/devcourse-Teemo/issues/68)

✨Feature: 시험장 생성 기능 구현 완료 / 코드 포매터 적용

---

src/api/invite.js
src/api/testCenter.js
src/pages/create-exam-room/CreateExamRoom.vue
src/pages/create-exam-room/components/SelectParticipants.vue

`feature/🚨Fix-create-exam-room` -> `dev`
시험장 생성시 초대된 사용자를 invite 테이블에 추가
(기존에는 시험장만 생성되고 invite가 안 됐었습니당)
처음부터 생각을 잘 해서 구현했으면 이렇게 수정할 일이 없었을텐데...ㅠ
feature/🚨Fix-create-exam-room #70 https://github.com/devcourse-Teemo/devcourse-Teemo/issues/70

:sparkles:Feature: 시험장 생성시 초대된 유저를 각각 invite 테이블에 추가

---

src/const/sorts.js

`fix/sort_initialize` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?

🚨 Fix: Sort가 초기화 이전에 사용돼서 페이지가 안 열리는 버그 수정

---

src/components/layout/LoginModal.vue

- 음... 저번 PR에 제가 `LoginModal`을 딱히 건든건 없는데, 아마두 이게 문젠 것 같아요!

🚨 Fix: 로그인 안되는 문제 수정

---

pnpm-lock.yaml
src/api/workbook.js

🐛 workbook.js error

---

src/api/invite.js
src/api/testCenter.js
src/pages/exam-room/ExamRoom.vue
src/pages/exam-room/components/ExamCard.vue
src/pages/exam-room/components/InvitedExamCard.vue
src/utils/formatDate.js
src/utils/formatDateForComment.js
src/utils/formatToKoreanDateTime.js

시험장 초대 -> 수락 / 거절 구현 
UI 즉시 업데이트 하도록 구현 
내가 만든 시험 -> 일정 지나면 안 보이도록 필터링  
_Invite.js에 코드 수정 -> getAll 하면 workbook title 가져오도록 수정_ 
-> 이 부분은 내 시험장 리스트에서 초대를 수락한 문제집에 title을 표시할 때 사용해서 추가했습니당  
[이슈 번호/정보](이슈 url) #62

✨Featue: 초대 수락/거절시 UI 업데이트 / 일정 지난 내가 만든 시험 필터링

---

src/api/invite.js
src/pages/exam-room/ExamRoom.vue
src/pages/exam-room/components/ExamCard.vue
src/pages/exam-room/components/InvitedExamCard.vue

`feature/exam-room` -> `dev`
<!-- PR에서 중점적으로 봐야할 부분이나 질문 & 애로사항 공유 -> 전달한 testCenterId와 일치하는 row 중 participate가 true인 값만 리턴
#62

✨Feature: 초대 수락한 인원을 카운트해서 표시 / 토스트 메시지

---

src/pages/create-exam-room/CreateExamRoom.vue

`feature/exam-room` -> `dev`
https://www.notion.so/QA-b05ee97254cb4c119a6bda04e8527ac1?pvs=4
새 시험장 생성시 formatToKoreanDateTime 사용해서 한국 시간대로 생성
#62

:rotating_light:Fix: 새 시험장 생성시 시간 포맷을 한국 시간대로 수정

---

src/pages/ExamMake.vue
src/pages/MyProblemSetsDetail.vue
src/pages/MyProblemsDetail.vue
src/router/index.js

`fix/router` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?

🚨 Fix: 라우팅 수정

---

src/api/testCenter.js
src/pages/exam-environment/ExamEnvironment.vue
src/pages/exam-environment/components/TestProblem.vue
src/store/examStore.js

`fix/exam-environment` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#97

✨ Feature: OX 문제 구현 및 제출하지 않은 답안을 유지하는 기능 구현 등

---

src/api/point.js

`fix/mypage` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#105

🚨 Fix: 포인트 내역의 정렬을 내림차순으로 변경

---

src/api/notification.js
src/components/layout/Notification.vue

`fix/notification` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#107

🚨 Fix: 알림 버그 2개 수정 및 모두 읽기 기능 추가

---

src/api/testResult.js
src/pages/exam-history/ExamHistory.vue
src/pages/exam-history/components/examHistoryTable.vue
src/pages/problem-board/ProblemBoard.vue
src/pages/problem-set-board/ProblemSetBoard.vue

`fix/exam-history` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#109

🚨 Fix: 키워드 검색 버그 및 날짜 검색 버그 수정 등

---

src/pages/NotFound.vue
src/pages/problem-editor/ProblemEditor.vue
src/pages/problem-editor/components/ProblemEditorGuide.vue
src/pages/problem-editor/components/ProblemEditorHeader.vue
src/pages/problem-editor/components/ProblemEditorLists.vue
src/pages/problem-editor/components/ProblemEditorMain.vue
src/store/authStore.js

117-fixproblemeditor -> `dev`
문제 생성 버그 수정 1차
- 문제 생성 시 필수 항목에 따라 제출 및 세션 저장 여부 수정
- 뒤로가기 로직 변경 (아무것도 없으면 저장 안됨)
- 제출시 경고 창, 제출 안됨 -> 에러 날 경우, 필수 항목이 누락될 경우
- 필수 항목이 누락될 경우 문제별, 인풋 항목별 빨간 border 표시
- 아무 문제도 선택되지 않을 경우에 guide 페이지 추가
- 필수 항목이 누락될 경우 알려주는 시점이 올바른가?
지금은 첫 입력 전에는 따로 red border를 주지 않음
- 경고 표시용 빨간 보더가 많아지면 눈아픔 
그대로 둘까요?
#117

🐛 fix: 문제 생성 필수 항목 추가, 페이지 이동 시 경고 및 확인 메시지 추가

---

src/api/problem.js
src/components/layout/ProblemTable.vue
src/pages/problem-board/ProblemBoard.vue
src/pages/problem-set-detail/ProblemSetDetail.vue

`fix/problem-board` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#120

🚨 Fix: 문제 게시판 상태 및 카테고리가 안 보이던 문제 해결

---

src/components/layout/ProblemTable.vue

💄 Style: 제목 컬럼 길이 CSS 재수정

---

src/api/workbookLike.js
src/pages/problem-set-detail/ProblemSetDetail.vue

🚨 fix: 문제집 상세 페이지 좋아요 기능 토글로 수정

---

src/api/againViewProblem.js
src/api/category.js
src/api/problem.js
src/components/layout/ProblemTable.vue
src/pages/my-problems/MyProblems.vue

`feature/my-problems` -> `dev`
보관한 문제 페이지 기능 구현
- 문제 불러오기
- 필터링
- 검색
=> 다시 볼 문제 / 내 문제만 보기 / 공유받은 문제 토글용 함수 추가
```
const handleFilterButtonClick = (filterType) => {
if (activeFilter.value === filterType) {
// 같은 버튼을 두 번 클릭하면 필터 해제
activeFilter.value = null;
emit("filter-change", "all");
} else {
// 새로운 필터 적용
activeFilter.value = filterType;
emit("filter-change", filterType);
}
};
```
=> `sortedProblems` 함수 수정
API 응답 구조에 따라 중첩 객체 구조로 되어있는 경우를 처리하기 위한 코드 추가
problem.likes[0]?.count가 있는 경우, problem.problem.likes[0]?.count가 있는 경우 (공유받은 문제)
이슈
다시 볼 문제로 등록한 문제는 중복 제거 안 됨
#112
https://github.com/devcourse-Teemo/devcourse-Teemo/issues/112

✨Feature: 보관한 문제 페이지 기능 구현

---

src/components/layout/ProblemTable.vue
src/components/layout/Search.vue
src/pages/my-problems/MyProblems.vue

`feature/my-problems` -> `dev`
- 검색 컴포넌트 높이 / round 맞춤 (Search.vue)
- 보관한 문제 페이지 카테고리 추가
- 문제 중복 제거
- 맞은 문제 / 틀린 문제 잘못 표시되는 버그 수정
- 필터링 버튼 클릭시 아이콘 색상 변경
맞은 문제 / 틀린 문제 잘못 표시되는 버그 부분 수정하고 테스트 후 PR 올리긴 했는데, 여유 되시면 테스트 해보시고 피드백 주시면 감사하겠습니다!

🚨Fix: 보관한 문제 페이지 카테고리 추가 / 보관한 문제 페이지 관련 QA

---

src/pages/exam-environment/ExamEnvironment.vue
src/pages/exam-environment/components/TestProblem.vue

`fix/exam-environment` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#139

🚨 Fix: 처음 진입하는 문제가 렌더링이 바로 안되는 버그 수정 및 다시 볼 문제 버튼 위치 변경

---

src/components/layout/ProblemTable.vue

`fix/problem-set-create-popup` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#143

🚨 Fix: 문제 추가 시, 내 문제집이 보이지 않던 버그 수정

---

src/api/problem.js
src/api/workbook.js
src/components/layout/Comment.vue
src/components/layout/ProblemTable.vue
src/pages/MyProblemSetsUpdate.vue
src/pages/problem-set-detail/ProblemSetDetail.vue
src/pages/problem-set-detail/components/CommentList.vue

🚨 Fix:문제집 상세 페이지, 문제집 수정 페이지 수정

---

src/components/layout/Notification.vue
src/pages/exam-environment/ExamEnvironment.vue
src/pages/problem-detail/ProblemBoardDetail.vue
src/pages/problem-detail/components/CommentList.vue
src/pages/problem-editor/ProblemEditor.vue
src/pages/problem-set-detail/components/CommentList.vue

`fix/notification` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#147

Fix: 알림을 눌렀을 때, 읽음 처리가 안되는 버그 수정 등

---

src/components/layout/Notification.vue
src/components/layout/ProblemTable.vue
src/pages/Mypage/components/MypageTabs.vue

`fix/notification` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?

🚨 Fix: 문제 유형에서 표의 스타일이 망가지는 버그 수정 및 알림 버그 2개 수정

---

src/api/testResult.js
src/pages/exam-history/components/examHistoryTable.vue

- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#155

🚨 Fix: 응시 일시가 예전 것부터 먼저 보여지던 버그 수정

---

src/api/problem.js
src/components/layout/ProblemSet.vue
src/components/layout/ProblemTable.vue
src/components/layout/Search.vue
src/pages/problem-board/ProblemBoard.vue
src/pages/problem-set-board/ProblemSetBoard.vue

`fix/problem-board` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#160

🚨 Fix: 페이지네이션이 유지가 안되던 버그 수정

---

src/pages/exam-room/ExamRoom.vue

버튼 정렬 space-between 제거 (다른 페이지와 통일)

:lipstick:Style: 전체보기 / 접기 버튼 위치 조정

---

src/pages/Mypage/components/MypageTabs.vue

`style/mypage-points` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#165

💄 Style: 등급 및 포인트 설명 디자인 수정

---

src/api/problemHistory.js
src/pages/exam-result/components/ExamResultProblems.vue
src/store/ExamResultStore.js

`fix/exam-result` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#168

🚨 Fix: 내가 제출한 답안이 다르게 표시되는 버그 수정

---

src/pages/Home.vue
src/pages/problem-editor/ProblemEditor.vue
src/pages/problem-editor/components/ProblemEditorHeader.vue
src/pages/problem-editor/components/ProblemEditorMain.vue
src/store/createProblemStore.js

`181-fixproblem-editor/` -> `dev`
- problem Editor 에디터 수정 안되는 오류 수정
- shared 삭제

181 fixproblem editor - problem Editor 오류 수정

---

src/pages/exam-result/ExamResult.vue
src/pages/exam-result/components/ExamResultHeader.vue

`style/exam-result` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#195

💄 Style: 시험 결과 페이지 디자인 수정

---

src/components/layout/ProblemSetPopUp.vue
src/pages/problem-editor/components/ProblemEditorHeader.vue
src/pages/problem-editor/components/ProblemEditorMain.vue

`181-fixproblem-editor/` -> `dev`
문제 에디터 버그 수정
- 카테고리 생성 시 글자 수 제한
- title 글자수 제한
- 빈 문자열 trim 처리로 인식
- 문제집 폴더가 confirm 창 위로 올라오는 문제 해결
- 빈 문제집 생성 막기
- problemSetPopup 수정
- problemEditorMain 수정
- problemEditorHeader 수정
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#181

Fix/Problem Editor 수정

---

src/api/testCenter.js

`fix/exam-environments` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#216

🚨 Fix: 시험 환경에서 problem.id로 정렬하도록 수정

---

src/pages/exam-result/components/ExamResultBody.vue
src/pages/problem-detail/ProblemBoardDetail.vue

`feature/exam-result` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#224

✨ Feature: 시험 결과가 실시간으로 반영되는 기능 추가

---

src/components/layout/Header.vue
src/main.js

`feature/point` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#226

✨ Feature: 포인트가 실시간으로 변경되는 기능 추가

---

README.md

📝 Chore: 리드미 수정

---

src/pages/exam-environment/components/TestSidebar.vue

`fix/exam-environment2/` -> `dev`
문제가 많을 때 시험환경 사이드바가 깨지는 오류를 해결했습니다.
- TestSideBar 문제 선택 레이아웃 스타일 수정
#236

🚨 Fix: 문제가 많을 경우 시험환경 사이트바 레이아웃 깨짐 해결
